### ISSUE TITLE
Use an ID for URL's instead of style's name

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#17]
For example if the style name changes, the old link wouldn't work anymore

Maybe just to keep the old links working, have a redirect to the new links

**Comment by VChet** [comment]
I don’t think that the names of the styles will change often, but it is still worth making an identifier that will never change.
The MongoDB ID is too long, I think the YouTube link format would be appropriate: an alphabet of uppercase and lowercase letters and numbers, 11 characters long ([collision calc](https://zelark.github.io/nano-id-cc/)). Any thoughts?

**Comment by RiedleroD** [comment]
Sounds good to me, there's a reason why youtube uses it. That website is dope btw, I love seeing demonstrations of stuff like this.

There's just the question left if user-selected IDs would be a good idea - I personally believe it to be a nice, unique feature, but could lead to confusion and/or people using it for malicious purposes. I doubt the latter is important though since there's not many people on stylebase, therefore reducing the chance that someone could actually succeed. I'd maybe add a 'regenerate ID' button for people that don't like the ID that they were given the first time. This would fix the problem of confusion by custom names, but also help people that have an indescribable hatred of - and _ in IDs (like me lol) and maybe people will choose to regenerate the ID when they see a swear word in the first ID, so that's a plus too.

**Comment by VChet** [comment]
Changed in [4.0.0](https://github.com/VChet/StyleBase/releases/tag/v4.0.0)
